<h1><b><font color = 'magenta'> Problem statement</h1>
    
   - We want to create a website where if user give one movie name then website will give him/her similar 5 movies based on tags

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credit = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
credit.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [5]:
movies.shape

(4803, 20)

In [6]:
credit.shape

(4803, 4)

In [7]:
movies = movies.merge(credit,on='title')

In [8]:
movies.shape

(4809, 23)

In [9]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

### Not Important column :
'budget','homepage','original_language', 'original_title','popularity','production_companies', 'production_countries','release_date','revenue','runtime', 'spoken_languages', 'status', 'tagline',  'vote_average','vote_count', 'movie_id'

<h1><font color ='DarkBlue'> Important columns to be consider :</h1>
    
     -  genres , id, keywords, title, overview ,cast,'crew',

In [11]:
movies = movies[['id','title','overview' ,'genres', 'keywords', 'cast','crew']]

In [12]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
movies.duplicated().sum()

0

In [17]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
#['Action','Adventure','Fantasy','Scifi']

In [19]:
import ast

In [20]:
#for genres and keyword columns
def convert(obj):
    l =[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [21]:
movies['genres'] = movies['genres'].apply(convert)

In [22]:
movies['keywords'] = movies['keywords'].apply(convert)

In [23]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
#for cast columns  to get top 3 actors in cast
def convert3(obj):
    l =[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            l.append(i['name'])
            counter+=1
        else:
            break
    return l

In [25]:
movies['cast'] = movies['cast'].apply(convert3)

In [26]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### To get director name filter crew column

In [27]:
def fetch_director(obj):
    l =[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [28]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [29]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [31]:
# it is string value so convert it into proper format

In [32]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [33]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [34]:
# Now we got list for every column and we want to create pragraph

In [35]:
# remove space between the words for better recomendation

In [36]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [37]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [38]:
# create column for pragraph
movies['tags'] = movies['overview']+ movies['genres']+ movies['keywords'] + movies['cast']+ movies['crew']

In [39]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [40]:
new_df = movies[['id','title','tags']]

In [41]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
# convert list in tags column to string format
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\user\AppData\Local\Temp\ipykernel_8672\877986308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [43]:
new_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [44]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [45]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\user\AppData\Local\Temp\ipykernel_8672\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [46]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [47]:
# apply stemming to remove similar words like [loved, loves] ->love
import nltk

D:\PGD\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [48]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [49]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [50]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\user\AppData\Local\Temp\ipykernel_8672\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

## Vectorization
 - to calculate similarity between text in tags column
 - convert text -> vector

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000,
                    stop_words='english')

In [52]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [53]:
#to get which 5000 words used as features
cv.get_feature_names()

D:\PGD\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [54]:
vectors.shape

(4806, 5000)

In [55]:
#we will calculate cosine distance between vectors i.e. angle between the two vectors

In [56]:
# it will check similarity of each movie with each other movies

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity = cosine_similarity(vectors)

In [59]:
list(enumerate(similarity[1]))

[(0, 0.08346223261119858),
 (1, 1.0),
 (2, 0.06063390625908323),
 (3, 0.03883678186903086),
 (4, 0.07504691899113898),
 (5, 0.1145873121285264),
 (6, 0.02127178149057585),
 (7, 0.1292719224987548),
 (8, 0.06262242910851494),
 (9, 0.10226199851298272),
 (10, 0.10846522890932808),
 (11, 0.07504691899113898),
 (12, 0.4140043409440133),
 (13, 0.09513029883089881),
 (14, 0.1355815361366601),
 (15, 0.1107018606925119),
 (16, 0.08346223261119858),
 (17, 0.2533201985524494),
 (18, 0.06021717344277752),
 (19, 0.1097907187727647),
 (20, 0.061357199107789626),
 (21, 0.05797710356524483),
 (22, 0.10502100630210075),
 (23, 0.09240616554505461),
 (24, 0.14097096860865022),
 (25, 0.1078676197944929),
 (26, 0.10846522890932808),
 (27, 0.08783257501821176),
 (28, 0.06160411036336974),
 (29, 0.04583492485141056),
 (30, 0.11778571185788637),
 (31, 0.10090091909944686),
 (32, 0.09007546982220897),
 (33, 0.10289915108550529),
 (34, 0.03300491809922247),
 (35, 0.10502100630210075),
 (36, 0.07845986714489121),
 (37, 0.05564148840746572),
 (38, 0.12862393885688161),
 (39, 0.05797710356524483),
 (40, 0.08134892168199606),
 (41, 0.10006255865485197),
 (42, 0.0),
 (43, 0.07204381596421111),
 (44, 0.03575992699260758),
 (45, 0.06534102628035482),
 (46, 0.11764705882352938),
 (47, 0.12478354962115543),
 (48, 0.11163607017227663),
 (49, 0.03080205518168487),
 (50, 0.08956221510397981),
 (51, 0.0425435629811517),
 (52, 0.07845986714489121),
 (53, 0.11357771260606365),
 (54, 0.03300491809922247),
 (55, 0.07440653318043244),
 (56, 0.07312724241271305),
 (57, 0.15339299776947407),
 (58, 0.09513029883089881),
 (59, 0.0958706236059213),
 (60, 0.0),
 (61, 0.140028008402801),
 (62, 0.13284223283101426),
 (63, 0.06482037235521643),
 (64, 0.03131121455425747),
 (65, 0.020646003475383347),
 (66, 0.11891287353862351),
 (67, 0.05797710356524483),
 (68, 0.0955394632947723),
 (69, 0.0700140042014005),
 (70, 0.053567158400558014),
 (71, 0.10341753799900383),
 (72, 0.11595420713048966),
 (73, 0.03500700210070025),
 (74, 0.07134772412317411),
 (75, 0.16477051091432687),
 (76, 0.050572173742417355),
 (77, 0.04565411576455765),
 (78, 0.053567158400558014),
 (79, 0.1097907187727647),
 (80, 0.03556714970147893),
 (81, 0.09709195467257715),
 (82, 0.026783579200279007),
 (83, 0.07134772412317411),
 (84, 0.08712136837380642),
 (85, 0.12065379433217113),
 (86, 0.05003127932742599),
 (87, 0.029411764705882346),
 (88, 0.0955394632947723),
 (89, 0.04565411576455765),
 (90, 0.09723055853282464),
 (91, 0.14705882352941174),
 (92, 0.06587443126365883),
 (93, 0.05003127932742599),
 (94, 0.16502459049611234),
 (95, 0.049507377148833714),
 (96, 0.08134892168199606),
 (97, 0.09799919151000504),
 (98, 0.13231403100624078),
 (99, 0.056388387443460086),
 (100, 0.03575992699260758),
 (101, 0.08134892168199606),
 (102, 0.06587443126365883),
 (103, 0.0844400661841498),
 (104, 0.14705882352941174),
 (105, 0.10969086361906957),
 (106, 0.13174886252731766),
 (107, 0.06534102628035482),
 (108, 0.05113099925649136),
 (109, 0.17149858514250882),
 (110, 0.023782574707724703),
 (111, 0.07938841860374446),
 (112, 0.05423261445466404),
 (113, 0.04583492485141056),
 (114, 0.04850712500726659),
 (115, 0.09249945801257606),
 (116, 0.05113099925649136),
 (117, 0.0939336436627724),
 (118, 0.017783574850739465),
 (119, 0.04583492485141056),
 (120, 0.0),
 (121, 0.11764705882352938),
 (122, 0.12320822072673948),
 (123, 0.047565149415449405),
 (124, 0.09513029883089881),
 (125, 0.09673824874398684),
 (126, 0.11277677488692017),
 (127, 0.11577058990186095),
 (128, 0.028583097523751468),
 (129, 0.14699878726500756),
 (130, 0.057166195047502935),
 (131, 0.08346223261119858),
 (132, 0.07134772412317411),
 (133, 0.05970814340265321),
 (134, 0.06859943405700353),
 (135, 0.0),
 (136, 0.09901475429766743),
 (137, 0.015923243882462048),
 (138, 0.16269784336399212),
 (139, 0.0850871259623034),
 (140, 0.047565149415449405),
 (141, 0.03080205518168487),
 (142, 0.08956221510397981),
 (143, 0.11458731212852641),
 (144, 0.05292561240249631),
 (145, 0.06105941257599791),
 (146, 0.017236256333167305),
 (147, 0.05882352941176469),
 (148, 0.06859943405700353),
 (149, 0.06149400462680908),
 (150, 0.09647549158488411),
 (151, 0.07151985398521515),
 (152, 0.08823529411764704),
 (153, 0.06239177481057771),
 (154, 0.03241018617760821),
 (155, 0.0),
 (156, 0.0422200330920749),
 (157, 0.0700140042014005),
 (158, 0.11778571185788639),
 (159, 0.06726727939963124),
 (160, 0.07075491376772249),
 (161, 0.03363363969981562),
 (162, 0.0700140042014005),
 (163, 0.026783579200279007),
 (164, 0.08458258116519013),
 (165, 0.024253562503633294),
 (166, 0.05292561240249631),
 (167, 0.1592324388246205),
 (168, 0.10585122480499262),
 (169, 0.11669000700233413),
 (170, 0.06755660236665673),
 (171, 0.12007302660701852),
 (172, 0.07484811885651196),
 (173, 0.04899959575500252),
 (174, 0.08238525545716345),
 (175, 0.05003127932742599),
 (176, 0.06160411036336974),
 (177, 0.0),
 (178, 0.10341753799900383),
 (179, 0.03834824944236852),
 (180, 0.023338001400466827),
 (181, 0.047565149415449405),
 (182, 0.07426106572325057),
 (183, 0.07440653318043244),
 (184, 0.053567158400558014),
 (185, 0.026783579200279007),
 (186, 0.041594516540385144),
 (187, 0.18981415059132412),
 (188, 0.023338001400466827),
 (189, 0.08084520834544433),
 (190, 0.1562904982411873),
 (191, 0.1292719224987548),
 (192, 0.05003127932742599),
 (193, 0.1332593209305539),
 (194, 0.0),
 (195, 0.06262242910851494),
 (196, 0.05492350363810897),
 (197, 0.07817631049941041),
 (198, 0.06063390625908323),
 (199, 0.27500954910846337),
 (200, 0.03834824944236852),
 (201, 0.0),
 (202, 0.03300491809922247),
 (203, 0.05882352941176469),
 (204, 0.02615328904829707),
 (205, 0.07868894753646336),
 (206, 0.09772038812426302),
 (207, 0.08134892168199606),
 (208, 0.09723055853282464),
 (209, 0.10727978097782273),
 (210, 0.05292561240249631),
 (211, 0.025854384499750957),
 (212, 0.046676002800933654),
 (213, 0.041594516540385144),
 (214, 0.0),
 (215, 0.09335200560186731),
 (216, 0.20579830217101058),
 (217, 0.06755660236665673),
 (218, 0.040422604172722164),
 (219, 0.06482037235521643),
 (220, 0.0939336436627724),
 (221, 0.05003127932742599),
 (222, 0.10555008273018725),
 (223, 0.05492350363810897),
 (224, 0.021437323142813602),
 (225, 0.049507377148833714),
 (226, 0.06369297552984819),
 (227, 0.11595420713048966),
 (228, 0.07001400420140048),
 (229, 0.0378777009539285),
 (230, 0.03883678186903086),
 (231, 0.0),
 (232, 0.11764705882352938),
 (233, 0.07312724241271305),
 (234, 0.11357771260606365),
 (235, 0.053567158400558014),
 (236, 0.030316953129541614),
 (237, 0.0700140042014005),
 (238, 0.07817631049941041),
 (239, 0.03859019663395365),
 (240, 0.09901475429766743),
 (241, 0.08346223261119858),
 (242, 0.08574929257125441),
 (243, 0.09799919151000504),
 (244, 0.03241018617760821),
 (245, 0.057166195047502935),
 (246, 0.08028956459037002),
 (247, 0.031846487764924096),
 (248, 0.04711428474315455),
 (249, 0.07312724241271305),
 (250, 0.03363363969981562),
 (251, 0.0),
 (252, 0.06431196942844081),
 (253, 0.044280744277004756),
 (254, 0.04899959575500252),
 (255, 0.026462806201248155),
 (256, 0.03934447376823168),
 (257, 0.056388387443460086),
 (258, 0.05613608914238397),
 (259, 0.06482037235521643),
 (260, 0.09240616554505461),
 (261, 0.02556549962824568),
 (262, 0.09007546982220897),
 (263, 0.10289915108550529),
 (264, 0.0),
 (265, 0.05797710356524483),
 (266, 0.05230657809659414),
 (267, 0.10289915108550529),
 (268, 0.05564148840746572),
 (269, 0.03131121455425747),
 (270, 0.09335200560186731),
 (271, 0.10006255865485197),
 (272, 0.0),
 (273, 0.0893088561378213),
 (274, 0.04067446084099803),
 (275, 0.030316953129541614),
 (276, 0.1320196723968899),
 (277, 0.03742405942825598),
 (278, 0.049507377148833714),
 (279, 0.04899959575500252),
 (280, 0.05492350363810897),
 (281, 0.04583492485141056),
 (282, 0.04711428474315455),
 (283, 0.028988551782622416),
 (284, 0.03883678186903086),
 (285, 0.06193801042615004),
 (286, 0.08258401390153339),
 (287, 0.027461751819054483),
 (288, 0.0),
 (289, 0.04850712500726659),
 (290, 0.06726727939963124),
 (291, 0.05292561240249631),
 (292, 0.0939336436627724),
 (293, 0.03131121455425747),
 (294, 0.09095085938862485),
 (295, 0.05564148840746572),
 (296, 0.06149400462680908),
 (297, 0.023338001400466827),
 (298, 0.0),
 (299, 0.06285566056425843),
 (300, 0.051708768999501914),
 (301, 0.039605901719066965),
 (302, 0.04899959575500252),
 (303, 0.029411764705882346),
 (304, 0.09737260471306503),
 (305, 0.06698164210336598),
 (306, 0.028583097523751468),
 (307, 0.08213292636386628),
 (308, 0.03575992699260758),
 (309, 0.06600983619844494),
 (310, 0.12964074471043285),
 (311, 0.026462806201248155),
 (312, 0.07938841860374446),
 (313, 0.0),
 (314, 0.0),
 (315, 0.11764705882352938),
 (316, 0.020951886854752806),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03500700210070025),
 (320, 0.03241018617760821),
 (321, 0.0),
 (322, 0.08346223261119858),
 (323, 0.03131121455425747),
 (324, 0.025854384499750957),
 (325, 0.140028008402801),
 (326, 0.029854071701326604),
 (327, 0.057166195047502935),
 (328, 0.05797710356524483),
 (329, 0.11128297681493143),
 (330, 0.10585122480499262),
 (331, 0.09513029883089881),
 (332, 0.08458258116519013),
 (333, 0.025854384499750957),
 (334, 0.10226199851298272),
 (335, 0.04899959575500252),
 (336, 0.07312724241271305),
 (337, 0.024014605321403704),
 (338, 0.0),
 (339, 0.07756315349925287),
 (340, 0.1569197342897824),
 (341, 0.05797710356524483),
 (342, 0.11363310286178552),
 (343, 0.04070627505066527),
 (344, 0.03131121455425747),
 (345, 0.04850712500726659),
 (346, 0.028988551782622416),
 (347, 0.0),
 (348, 0.06482037235521643),
 (349, 0.10713431680111603),
 (350, 0.051708768999501914),
 (351, 0.024014605321403704),
 (352, 0.05797710356524483),
 (353, 0.021780342093451605),
 (354, 0.0),
 (355, 0.05788529495093047),
 (356, 0.06369297552984819),
 (357, 0.0),
 (358, 0.06369297552984819),
 (359, 0.1320196723968899),
 (360, 0.0),
 (361, 0.10585122480499262),
 (362, 0.03363363969981562),
 (363, 0.04190377370950561),
 (364, 0.049507377148833714),
 (365, 0.0),
 (366, 0.029854071701326604),
 (367, 0.0),
 (368, 0.06859943405700353),
 (369, 0.08134892168199606),
 (370, 0.053567158400558014),
 (371, 0.050572173742417355),
 (372, 0.05003127932742599),
 (373, 0.0),
 (374, 0.08028956459037002),
 (375, 0.02160679078507214),
 (376, 0.049507377148833714),
 (377, 0.02449979787750126),
 (378, 0.03241018617760821),
 (379, 0.08939981748151894),
 (380, 0.027461751819054483),
 (381, 0.08856148855400951),
 (382, 0.0),
 (383, 0.06875238727711584),
 (384, 0.12126781251816646),
 (385, 0.030316953129541614),
 (386, 0.06937459350943204),
 (387, 0.025015639663712994),
 (388, 0.024253562503633294),
 (389, 0.12320822072673948),
 (390, 0.02782074420373286),
 (391, 0.07974522228289),
 (392, 0.09553946329477228),
 (393, 0.0),
 (394, 0.02615328904829707),
 (395, 0.0),
 (396, 0.023124864503144014),
 (397, 0.05492350363810897),
 (398, 0.046676002800933654),
 (399, 0.025015639663712994),
 (400, 0.06369297552984819),
 (401, 0.0),
 (402, 0.05492350363810897),
 (403, 0.1097907187727647),
 (404, 0.0),
 (405, 0.05882352941176469),
 (406, 0.0),
 (407, 0.06755660236665673),
 (408, 0.034299717028501764),
 (409, 0.049507377148833714),
 (410, 0.051708768999501914),
 (411, 0.08346223261119858),
 (412, 0.15171652122725207),
 (413, 0.05970814340265321),
 (414, 0.03131121455425747),
 (415, 0.018824415287446383),
 (416, 0.053567158400558014),
 (417, 0.034299717028501764),
 (418, 0.03742405942825598),
 (419, 0.07276068751089988),
 (420, 0.09513029883089881),
 (421, 0.0),
 (422, 0.03080205518168487),
 (423, 0.04356068418690321),
 (424, 0.03934447376823168),
 (425, 0.09007546982220897),
 (426, 0.056816551430892745),
 (427, 0.08346223261119858),
 (428, 0.059016710652347516),
 (429, 0.0),
 (430, 0.0),
 (431, 0.05113099925649136),
 (432, 0.04802921064280741),
 (433, 0.03300491809922247),
 (434, 0.025015639663712994),
 (435, 0.07484811885651196),
 (436, 0.02711630722733202),
 (437, 0.05423261445466404),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.024014605321403704),
 (443, 0.06755660236665673),
 (444, 0.024753688574416857),
 (445, 0.02615328904829707),
 (446, 0.02449979787750126),
 (447, 0.04543108504242546),
 (448, 0.045037734911104486),
 (449, 0.028988551782622416),
 (450, 0.022518867455552243),
 (451, 0.026462806201248155),
 (452, 0.03241018617760821),
 (453, 0.025854384499750957),
 (454, 0.049507377148833714),
 (455, 0.042874646285627205),
 (456, 0.02291746242570528),
 (457, 0.12126781251816646),
 (458, 0.04583492485141056),
 (459, 0.03656362120635653),
 (460, 0.05113099925649136),
 (461, 0.08956221510397981),
 (462, 0.034129494057038114),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.07669649888473704),
 (467, 0.06698164210336598),
 (468, 0.05882352941176469),
 (469, 0.08380754741901122),
 (470, 0.04802921064280741),
 (471, 0.09007546982220897),
 (472, 0.11277677488692017),
 (473, 0.04899959575500252),
 (474, 0.0),
 (475, 0.06937459350943204),
 (476, 0.03575992699260758),
 (477, 0.0),
 (478, 0.057166195047502935),
 (479, 0.03720326659021622),
 (480, 0.07756315349925287),
 (481, 0.025015639663712994),
 (482, 0.0),
 (483, 0.09901475429766741),
 (484, 0.06160411036336974),
 (485, 0.08346223261119858),
 (486, 0.10138954626279946),
 (487, 0.06726727939963124),
 (488, 0.05278615073083401),
 (489, 0.042874646285627205),
 (490, 0.07484811885651196),
 (491, 0.06285566056425843),
 (492, 0.08035073760083702),
 (493, 0.03241018617760821),
 (494, 0.03575992699260758),
 (495, 0.06726727939963124),
 (496, 0.017977936632415484),
 (497, 0.034299717028501764),
 (498, 0.07151985398521515),
 (499, 0.02782074420373286),
 (500, 0.027461751819054483),
 (501, 0.06482037235521643),
 (502, 0.04711428474315455),
 (503, 0.07938841860374446),
 (504, 0.03241018617760821),
 (505, 0.07151985398521515),
 (506, 0.0),
 (507, 0.06755660236665673),
 (508, 0.13391789600139503),
 (509, 0.07001400420140048),
 (510, 0.02615328904829707),
 (511, 0.09723055853282464),
 (512, 0.028988551782622416),
 (513, 0.05230657809659414),
 (514, 0.07845986714489121),
 (515, 0.05230657809659414),
 (516, 0.0),
 (517, 0.06333004963811235),
 (518, 0.04624972900628803),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.05113099925649136),
 (524, 0.03080205518168487),
 (525, 0.025015639663712994),
 (526, 0.0),
 (527, 0.0),
 (528, 0.023557142371577276),
 (529, 0.025286086871208677),
 (530, 0.08823529411764704),
 (531, 0.04899959575500252),
 (532, 0.0),
 (533, 0.031846487764924096),
 (534, 0.044280744277004756),
 (535, 0.051708768999501914),
 (536, 0.023782574707724703),
 (537, 0.07151985398521515),
 (538, 0.0),
 (539, 0.05882352941176469),
 (540, 0.05292561240249631),
 (541, 0.04465442806891065),
 (542, 0.05863223287455781),
 (543, 0.12507819831856498),
 (544, 0.08823529411764704),
 (545, 0.02615328904829707),
 (546, 0.06726727939963124),
 (547, 0.08823529411764704),
 (548, 0.0),
 (549, 0.07585826061362604),
 (550, 0.0),
 (551, 0.07974522228289),
 (552, 0.0),
 (553, 0.030316953129541614),
 (554, 0.029854071701326604),
 (555, 0.0158550498051498),
 (556, 0.028194193721730043),
 (557, 0.025854384499750957),
 (558, 0.0),
 (559, 0.031846487764924096),
 (560, 0.057166195047502935),
 (561, 0.03363363969981562),
 (562, 0.03241018617760821),
 (563, 0.05423261445466404),
 (564, 0.03131121455425747),
 (565, 0.06875238727711584),
 (566, 0.07585826061362604),
 (567, 0.0),
 (568, 0.05970814340265321),
 (569, 0.10006255865485197),
 (570, 0.03575992699260758),
 (571, 0.022327214034455325),
 (572, 0.09086217008485092),
 (573, 0.02195814375455294),
 (574, 0.024753688574416857),
 (575, 0.04802921064280741),
 (576, 0.05492350363810897),
 (577, 0.05970814340265321),
 (578, 0.039605901719066965),
 (579, 0.03080205518168487),
 (580, 0.02556549962824568),
 (581, 0.12320822072673948),
 (582, 0.04711428474315455),
 (583, 0.11961783342433499),
 (584, 0.08574929257125441),
 (585, 0.025854384499750957),
 (586, 0.047565149415449405),
 (587, 0.12507819831856498),
 (588, 0.02711630722733202),
 (589, 0.040996003084539386),
 (590, 0.031846487764924096),
 (591, 0.044280744277004756),
 (592, 0.06698164210336598),
 (593, 0.020072391147592506),
 (594, 0.05230657809659414),
 (595, 0.04850712500726659),
 (596, 0.09799919151000504),
 (597, 0.0939336436627724),
 (598, 0.0),
 (599, 0.014494275891311208),
 (600, 0.04850712500726659),
 (601, 0.05306618532579187),
 (602, 0.07204381596421111),
 (603, 0.057166195047502935),
 (604, 0.0700140042014005),
 (605, 0.0),
 (606, 0.0),
 (607, 0.10176568762666317),
 (608, 0.0),
 (609, 0.049507377148833714),
 (610, 0.07669649888473704),
 (611, 0.02449979787750126),
 (612, 0.0893088561378213),
 (613, 0.03742405942825598),
 (614, 0.051708768999501914),
 (615, 0.03241018617760821),
 (616, 0.03656362120635653),
 (617, 0.026462806201248155),
 (618, 0.09335200560186731),
 (619, 0.05423261445466404),
 (620, 0.0),
 (621, 0.034299717028501764),
 (622, 0.022327214034455325),
 (623, 0.047565149415449405),
 (624, 0.07312724241271305),
 (625, 0.0),
 (626, 0.028988551782622416),
 (627, 0.11504474832710555),
 (628, 0.051708768999501914),
 (629, 0.05113099925649136),
 (630, 0.025854384499750957),
 (631, 0.026783579200279007),
 (632, 0.0),
 (633, 0.04711428474315455),
 (634, 0.05230657809659414),
 (635, 0.023338001400466827),
 (636, 0.07426106572325057),
 (637, 0.0),
 (638, 0.0),
 (639, 0.02556549962824568),
 (640, 0.06333004963811235),
 (641, 0.0),
 (642, 0.03080205518168487),
 (643, 0.07938841860374446),
 (644, 0.05292561240249631),
 (645, 0.07001400420140048),
 (646, 0.08346223261119858),
 (647, 0.0),
 (648, 0.0),
 (649, 0.10846522890932808),
 (650, 0.05492350363810897),
 (651, 0.08035073760083702),
 (652, 0.0),
 (653, 0.03834824944236852),
 (654, 0.08783257501821176),
 (655, 0.025286086871208677),
 (656, 0.025854384499750957),
 (657, 0.07312724241271305),
 (658, 0.07669649888473704),
 (659, 0.10713431680111603),
 (660, 0.09901475429766741),
 (661, 0.08856148855400951),
 (662, 0.0),
 (663, 0.0),
 (664, 0.12738595105969638),
 (665, 0.07204381596421111),
 (666, 0.05292561240249631),
 (667, 0.0),
 (668, 0.07151985398521515),
 (669, 0.0),
 (670, 0.0),
 (671, 0.024014605321403704),
 (672, 0.029854071701326604),
 (673, 0.0),
 (674, 0.05003127932742599),
 (675, 0.047565149415449405),
 (676, 0.06063390625908323),
 (677, 0.026462806201248155),
 (678, 0.06160411036336974),
 (679, 0.0),
 (680, 0.026462806201248155),
 (681, 0.0),
 (682, 0.0),
 (683, 0.05113099925649136),
 (684, 0.0),
 (685, 0.034299717028501764),
 (686, 0.06726727939963124),
 (687, 0.05492350363810897),
 (688, 0.02291746242570528),
 (689, 0.053567158400558014),
 (690, 0.05292561240249631),
 (691, 0.0939336436627724),
 (692, 0.023124864503144014),
 (693, 0.0),
 (694, 0.11562432251572008),
 (695, 0.10502100630210075),
 (696, 0.04543108504242546),
 (697, 0.07817631049941041),
 (698, 0.04583492485141056),
 (699, 0.0),
 (700, 0.06063390625908323),
 (701, 0.0),
 (702, 0.047565149415449405),
 (703, 0.02271554252121273),
 (704, 0.024014605321403704),
 (705, 0.051708768999501914),
 (706, 0.04583492485141056),
 (707, 0.06859943405700353),
 (708, 0.02615328904829707),
 (709, 0.04356068418690321),
 (710, 0.04070627505066527),
 (711, 0.08346223261119858),
 (712, 0.02556549962824568),
 (713, 0.0),
 (714, 0.0),
 (715, 0.10502100630210075),
 (716, 0.08574929257125441),
 (717, 0.09249945801257606),
 (718, 0.023782574707724703),
 (719, 0.041594516540385144),
 (720, 0.0),
 (721, 0.034299717028501764),
 (722, 0.07276068751089988),
 (723, 0.0),
 (724, 0.07504691899113898),
 (725, 0.0),
 (726, 0.0),
 (727, 0.032555850669650596),
 (728, 0.07669649888473704),
 (729, 0.0),
 (730, 0.07996162762590017),
 (731, 0.08238525545716345),
 (732, 0.04802921064280741),
 (733, 0.06482037235521643),
 (734, 0.07067142711473183),
 (735, 0.023557142371577276),
 (736, 0.0939336436627724),
 (737, 0.05423261445466404),
 (738, 0.07312724241271305),
 (739, 0.040422604172722164),
 (740, 0.04583492485141056),
 (741, 0.05882352941176469),

In [60]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]#to get movie index
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [61]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [62]:
recommend('Batman')

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.

In [65]:
import pickle

In [67]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [68]:
pickle.dump(similarity,open('similarity.pkl','wb'))